# Generated by Django 4.1.6 on 2023-02-03 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("item_pedido", "0001_initial"),
        ("endereco", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrinho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Total: ",
                    ),
                ),
                (
                    "usa_transportadora",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Usa Transportadora: ",
                    ),
                ),
                (
                    "pago",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Pago: "
                    ),
                ),
                (
                    "entregue",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Entregue: "
                    ),
                ),
                (
                    "devolvido",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Devolvido: "
                    ),
                ),
                (
                    "endereco_devolucao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="endereco.endereco",
                        verbose_name="Endereço para devolução: ",
                    ),
                ),
                (
                    "endereco_entrega",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="endereco.endereco",
                        verbose_name="Endereço para entrega: ",
                    ),
                ),
                (
                    "item_pedido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="item_pedido.itempedido",
                        verbose_name="Item Pedido: ",
                    ),
                ),
            ],
        ),
    ]
