# Generated by Django 4.1.6 on 2023-02-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0001_initial"),
        ("estoque", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="estoque",
            name="lista_itens",
            field=models.ManyToManyField(
                blank=True, to="item.item", verbose_name="lista de itens:"
            ),
        ),
    ]
