# Generated by Django 4.1.6 on 2023-02-03 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("endereco", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Nome: "
                    ),
                ),
                (
                    "cpf_cnpj",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Cpf ou CNPJ: "
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        choices=[("1", "Locador"), ("2", "Locatário")],
                        max_length=20,
                        null=True,
                        verbose_name="Nome do Produto",
                    ),
                ),
                ("email", models.CharField(max_length=50, verbose_name="Email: ")),
                ("senha", models.CharField(max_length=20, verbose_name="Senha: ")),
                (
                    "logado",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Usuário Logado: ",
                    ),
                ),
                (
                    "endereco",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="endereco.endereco",
                        verbose_name="Endereço do usuário: ",
                    ),
                ),
            ],
        ),
    ]
