# Generated by Django 4.1.6 on 2023-02-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Locador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "itens_escolhidos",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="item.item",
                        verbose_name="lista de itens:",
                    ),
                ),
            ],
        ),
    ]
