# Generated by Django 4.1.6 on 2023-02-03 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("endereco", "0001_initial"),
        ("carrinho", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Locador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usa_transportadora",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Usa Transportadora: ",
                    ),
                ),
                (
                    "carrinho",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="carrinho.carrinho",
                        verbose_name="Carrinho: ",
                    ),
                ),
                (
                    "endereco_devolucao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="endereco.endereco",
                        verbose_name="Endereço para devolução: ",
                    ),
                ),
                (
                    "endereco_entrega",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="endereco.endereco",
                        verbose_name="Endereço para entrega: ",
                    ),
                ),
            ],
        ),
    ]
