# Generated by Django 4.1.6 on 2023-02-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0001_initial"),
        ("locador", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locador",
            name="itens_escolhidos",
            field=models.ManyToManyField(
                blank=True, to="item.item", verbose_name="lista de itens:"
            ),
        ),
    ]
