# Generated by Django 4.1.6 on 2023-02-06 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0001_initial"),
        ("locador", "0002_alter_locador_itens_escolhidos"),
    ]

    operations = [
        migrations.AddField(
            model_name="locador",
            name="nome_locador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usuario.usuario",
                verbose_name="nome do locador",
            ),
        ),
    ]
