# Generated by Django 4.1.6 on 2023-02-06 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0001_initial"),
        ("locador", "0003_locador_nome_locador"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locador",
            name="itens_escolhidos",
        ),
        migrations.AddField(
            model_name="locador",
            name="produto",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="item.item"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="locador",
            name="quantidade",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
