# Generated by Django 4.1.6 on 2023-02-06 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locatario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Nome do item",
                    ),
                ),
                (
                    "quantidade",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Quantidade de itens",
                    ),
                ),
                (
                    "preco",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="Preço do produto",
                    ),
                ),
                (
                    "disponivel",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Item disponível?",
                    ),
                ),
                (
                    "alugado",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Item alugado?",
                    ),
                ),
                (
                    "entregue",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Item entregue?",
                    ),
                ),
                (
                    "quantidade_pedida",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Quantidade de itens pedidos",
                    ),
                ),
                (
                    "quantidade_restante",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Quantidade restatnte de itens",
                    ),
                ),
                (
                    "midia",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="imagens",
                        verbose_name="Fotos e Documentos",
                    ),
                ),
                (
                    "dono",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="locatario.locatario",
                        verbose_name="Dono do item",
                    ),
                ),
            ],
        ),
    ]
