# Generated by Django 4.1.6 on 2023-02-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="disponível",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Item disponível?"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="nome",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Nome do item"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="preco",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=9,
                null=True,
                verbose_name="Preço do produto",
            ),
        ),
    ]
