# Generated by Django 4.1.6 on 2023-02-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_disponível_item_nome_item_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='itens'),
        ),
    ]
