# Generated by Django 4.1.6 on 2023-02-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='foto',
        ),
        migrations.AddField(
            model_name='item',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de itens'),
        ),
        migrations.AddField(
            model_name='item',
            name='quantidade_restante',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de itens restantes'),
        ),
    ]
