# Generated by Django 4.1.6 on 2023-02-03 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_itempedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='disponível',
            new_name='disponivel',
        ),
    ]
