# Generated by Django 4.1.6 on 2023-02-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0006_rename_disponível_item_disponivel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ItemPedido",
        ),
    ]
