# Generated by Django 4.1.6 on 2023-02-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0008_remove_item_quantidade_restante_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="quantidade_restante",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Quantidade restatnte de itens"
            ),
        ),
    ]
