# Generated by Django 4.1.6 on 2023-02-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0009_item_quantidade_restante"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="quantidade_restante",
            field=models.IntegerField(
                blank=True,
                default=1,
                null=True,
                verbose_name="Quantidade restatnte de itens",
            ),
        ),
    ]
